<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>m3u</string>
		<string>m3u8</string>
	</array>
	<key>name</key>
	<string>M3U</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^[ \t].*</string>
			<key>name</key>
			<string>invalid.illegal.m3u</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^#EXTM3U$</string>
			<key>name</key>
			<string>support.class.m3u</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^#EXTINF</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.constant.m3u</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(,)(.*)|$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.m3u</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.value.m3u</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.extinf.m3u</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>keyword.control.m3u</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-?[\d\.]+</string>
					<key>name</key>
					<string>constant.numeric.m3u</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^#EXT[-\w]*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.constant.m3u</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.function.ext.m3u</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>keyword.control.m3u</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[=,@]</string>
					<key>name</key>
					<string>keyword.operator.m3u</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([^=,@])|.*</string>
					<key>name</key>
					<string>meta.value.m3u</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^[^#].+</string>
			<key>name</key>
			<string>string.unquoted.m3u</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.m3u</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.m3u</string>
	<key>uuid</key>
	<string>9d842cd7-2bc7-4e27-b6a1-4ff187ab3a04</string>
</dict>
</plist>
